title: "עמוק בעמק · Nel profondo della valle"
description: "הגות בוולססיה · Riflessioni in Valsesia"
lang: he
url: "https://dror27.github.io"
baseurl: "/valsesia"
timezone: Europe/Rome
markdown: kramdown
permalink: pretty

collections:
  essays_he:
    output: true
    permalink: /he/:path/
  essays_it:
    output: true
    permalink: /it/:path/
  essays_en:
    output: true
    permalink: /en/:path/

defaults:
  - scope:
      path: ""
      type: essays_he
    values:
      layout: essay
      lang: he
      text_dir: rtl
  - scope:
      path: ""
      type: essays_it
    values:
      layout: essay
      lang: it
      text_dir: ltr
  - scope:
      path: ""
      type: essays_en
    values:
      layout: essay
      lang: en
      text_dir: ltr

exclude:
  - README.md
